# Generated by Django 3.0.8 on 2020-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('meaning', models.TextField()),
                ('sentence1', models.TextField()),
                ('sentence2', models.TextField()),
                ('etymology', models.TextField()),
                ('mnemonic', models.TextField()),
                ('hardness_level', models.IntegerField()),
            ],
        ),
    ]
